baseURL = 'https://reviz-tw.github.io/reviz/'
title = 'reviz'

defaultContentLanguage = 'zh-TW'
defaultContentLanguageInSubdir = false

[languages]
  [languages.zh-TW]
    languageName = '繁體中文'
    languageCode = 'zh-TW'
    weight = 1
    title = 'reviz'
  [languages.en]
    languageName = 'English'
    languageCode = 'en'
    weight = 2
    title = 'reviz'
  [languages.ja]
    languageName = '日本語'
    languageCode = 'ja'
    weight = 3
    title = 'reviz'
  [languages.ko]
    languageName = '한국어'
    languageCode = 'ko'
    weight = 4
    title = 'reviz'

[params]
  author = "reviz studio"
